---
abstract: 'Split ESLPodcast into fast, slow and explanation dialogs.'
author:
  - 'Yohei Yamaguchi <joker13meister@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Podcast-ESLPodcast-Splitter
provides:
  Podcast::ESLPodcast::Splitter:
    file: lib/Podcast/ESLPodcast/Splitter.pm
    version: v0.0.1
requires:
  Test::More: 0
  version: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: v0.0.1
